// Generated by https://quicktype.io

export interface Latest {
    success:   boolean;
    timestamp: number;
    base:      string;
    date:      string;
    rates:     Rate;
}


export interface Rate {
    rates: { [key: string]: number }
}

